config/routes.rb
LibraryThing::Application.routes.draw do

  root 'site#start'

  get 'login' => 'users#login'
  get 'logout' => 'sessions#destroy', as: :signout  

  get '/auth/github/' => redirect('/auth/github')
  get '/auth/github/callback', to: 'sessions#create'
  get '/auth/failure' => redirect('/')

  
  

  resources :libraries
  resources :students
  resources :books

  post 'libraries/:id/checkout_confirm' => 'libraries#checkout_confirm'
  post 'libraries/:id/return_confirm' => 'libraries#return_confirm'

end

app/models/library.rb
# == Schema Information
#
# Table name: libraries
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  name       :string(255)
#

class Library < ActiveRecord::Base
  has_many :books

  # def make_book_unavailable(book)
  #   LibraryBook.where(:book_id => book.id).first.available = false
  # end

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  skip_before_filter :verify_authenticity_token

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
    if params[:book_checkout]
      @library = Library.find(params[:id])
      @student = Student.find(params[:student][:student_id])
      @books = Book.where(:available => true)
      render :checkout_select
    elsif params[:book_return]
      @library = Library.find(params[:id])
      @student = Student.find(params[:student][:student_id])
      #AND the student has checkedout books
      if @student.books.length > 0
      #keep going if student has books to return   
        render :return_select
      else 
        #display a message and do not leave home page
        redirect_to root_url, notice: "you do not have any books checkedout"
      end
    else 
      render :browse
    end
  end

  def checkout_select
  end

  def checkout_confirm
   #    {"books"=>{"book_id"=>["1", "5", "8"]},
   # "student_id"=>"4",
   # "commit"=>"Check out selected books",
   # "controller"=>"libraries",
   # "action"=>"checkout_confirm",
   # "id"=>"1"}  

    @library = Library.find(params[:id])
    @student = Student.find(params[:student_id])
    
    # get all books from books[:book_id][in here]
    selected_books = params[:books][:book_id]
    @checkedout_books = []

    selected_books.each do |book_id|
      @student.checkout_books.build(:book_id => book_id)
      book = Book.find(book_id)
      book.available = false
      book.save
      @checkedout_books << book
    end

    @student.save
    
  end

  def return_select
  end

  def return_confirm
    @library = Library.find(params[:id])
    @student = Student.find(params[:student_id])
    @book = Book.find(params[:books][:book_id])

    selected_books = params[:books][:book_id]
    @returned_books = []

    selected_books.each do |book_id|
      book_to_return = @student.checkout_books(:book_id => book_id)
      book_to_return.delete
      book = Book.find(book_id)
      book.available = true
      book.save
      @returned_books << book
    end

    @student.save

  end

  def browse
    #currently using show to redirect based on user action so may need a separate action for simply browsing books in the library
  end


  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render action: 'show', status: :created, location: @library }
      else
        format.html { render action: 'new' }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% @library.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libraries/checkout-old.html.erb
<p id="notice"><%= notice %></p>
 <h1><%= @library.name %> Library</h1>
 <h2>Hi <%= @student.name %>, please select a book to check out</h2>

<form action="<%= @library.id %>/checkout" method="post" accept-charset="utf-8">
<ul class="pick-list" id="book-list">
<% @library.books.each do |book| 
    book_label_id = "books_book_id_ #{book.id}"
    %>
  <label><li><%= radio_button_tag("books[book_id]", book.id) %> <em><%= book.title %></em>, by <%= book.author %></li></label>
  <% end %>
</ul>

<input type="hidden" name="student_id" value="<%= @student.id %>">

  <p>
    <%= submit_tag "Check out the selected book", class:"submit-button" %>
  </p>
</form>

app/views/libraries/checkout.html.erb
<p id="notice"><%= notice %></p>
 <h1><%= @library.name %> Library</h1>
 <h2>Hi <%= @student.name %>, please select a book to check out</h2>

<form action="<%= @library.id %>/checkout" method="post" accept-charset="utf-8">
<ul class="pick-list" id="book-list">
<% @library.books.each do |book| 
    book_label_id = "books_book_id_ #{book.id}"
    %>
  <label><li><%= radio_button_tag("books[book_id]", book.id) %> <em><%= book.title %></em>, by <%= book.author %></li></label>
  <% end %>
</ul>

  <p>
    <%= submit_tag "Check out the selected book", class:"submit-button" %>
  </p>
</form>

app/views/libraries/checkout_confirm.html.erb
<h1>Hi <%= @student.name %>, you've checked out the following books:</h1>
<ul>
<% @checkedout_books.each do |book| %>
  <li><%= book.title %></li>
  <% end %>
</ul>

<p>Please don't forget to return these books or Avi will find you :-)</p>
<p><input type="button" value="Back to Library" name="ClickBack" onclick=(history.back())>
</p>

app/views/libraries/checkout_select.html.erb
<script>
function goBack()
  {
  window.history.back()
  }
</script>
 <h2>Hi <%= @student.name %>, please select the books you'd like to check out:</h2>

<form action="<%= @library.id %>/checkout_confirm" method="post" accept-charset="utf-8">
<ul class="pick-list" id="book-list">

<% @books.each do |book| 
    book_label_id = "books_book_id_ #{book.id}"
    %>
    
  <li><label> <%= check_box_tag("books[book_id][]", book.id) %> <em><%= book.title %></em>, by <%= book.authors %></label></li>
  <% end %>
</ul>
<input type="hidden" name="student_id" value="<%= @student.id %>">

  <p>
    <%= submit_tag "Check out selected books", class:"submit-button btn btn-success" %>
  </p>
</form>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<h1>Listing libraries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
      <td><%= library.name %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render 'form' %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/return_confirm.html.erb
<h1>Hi <%= @student.name %>, you've returned the following book(s):</h1>

<ul>
<% @returned_books.each do |book| %>
  <li><%= book.title %></li>
  <% end %>
</ul>

<p>Thanks!</p>
<p><input type="button" value="Back to Library" name="ClickBack" onclick=(history.back())></p>

app/views/libraries/return_select.html.erb
 <h2>Hi <%= @student.name %>, please select the book you'd like to return:</h2>

<form action="<%= @library.id %>/return_confirm" method="post" accept-charset="utf-8">
<ul class="pick-list" id="book-list">

<% @student.books.each do |book| 
    book_label_id = "books_book_id_ #{book.id}"
    %>
    
  <li><label> <%= check_box_tag("books[book_id][]", book.id) %> <em><%= book.title %></em>, by <%= book.authors %></label></li>
  <% end %>
</ul>
<input type="hidden" name="student_id" value="<%= @student.id %>">

  <p>
    <%= submit_tag "Return the selected book", class:"submit-button btn btn-success" %>
  </p>
</form>

app/views/libraries/show.html.erb
 <!-- placeholder for libraries  -->


<%# link_to 'Edit', edit_library_path(@library) %> <!-- | -->
<%# link_to 'Back', libraries_path %>